### ISSUE TITLE
[C4GT Community]: Global search filter for Story list

### ISSUE THREAD

**Issue by gouravmore** [Sunbird-ALL/all-config-app#10]
## Description
The project aims to implement a global search filter for the story list table structure in our application. This feature is essential for users to quickly find specific stories based on various criteria.

### Goals
 
- [ ] Implement global search functionality for the story list.
- [ ]  Enable users to search by story title, author, date, and other relevant criteria.
- [ ]  Enhance user experience by providing quick and accurate search results.

### Expected Outcome

The final product should include a search bar within the story list interface, allowing users to enter keywords and filter the displayed stories accordingly. The search results should update dynamically as the user types, providing instant feedback.

### Acceptance Criteria

- The global search feature should accurately filter the list of stories based on user input.
- Users should be able to search by story title, author, date, and any other relevant attributes.
- The search results should update in real-time as the user types, without the need for manual refresh.

### Implementation Details

- [ ] The global search functionality will be implemented using Primeng angular lib and Javascript for dynamic updates.
- [ ] Backend APIs will be utilized to fetch filtered data based on user search queries.
- [ ] The search algorithm will prioritize relevant matches and provide suggestions as the user types.

### Mockups/Wireframes

![storylistView](https://github.com/Sunbird-ALL/all-config-app/assets/16605526/4a6e6473-cf3a-4f07-b827-c2643b4d2564)

### Product Name

Assistance language learning - content creation app

### Organisation Name

Tekdi

### Tech Skills Needed

Angular

### Mentor(s)

@gouravmore @DevendraPPatil
### Complexity

Medium

### Category

Frontend

**Comment by MjStar24** [comment]
hey @gouravmore I would like to work on this ticket . i have gone through the code base can you assign this to me

**Comment by sid-nc** [comment]
@gouravmore Can I get assigned to this

**Comment by rising0raj** [comment]
hey @gouravmore I would like to work on this . I have gone through the code base can you assign this to me if it is open??

**Comment by thakur24** [comment]
Hi @gouravmore / Team , I'm trying to setup the project in local. And facing this issue. Can you pls help on this . Thanks !
![image](https://github.com/Sunbird-ALL/all-config-app/assets/43248093/7ae0f135-461f-47aa-876a-0026ec9fd1da)

**Comment by surajgorai2002** [comment]
> Hi @gouravmore / Team , I'm trying to setup the project in local. And facing this issue. Can you pls help on this . Thanks ! ![image](https://private-user-images.githubusercontent.com/43248093/313617318-7ae0f135-461f-47aa-876a-0026ec9fd1da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTcwNTksIm5iZiI6MTcxMDc5Njc1OSwicGF0aCI6Ii80MzI0ODA5My8zMTM2MTczMTgtN2FlMGYxMzUtNDYxZi00N2FhLTg3NmEtMDAyNmVjOWZkMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIxMTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjODZkMjYyMTMwY2FlNTJkMDE0MTMxZDJjZTVjZDc0Zjg0MzJlMGI0NWRjM2I2NTQ5M2I4ZWQwMzEzNzAxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yU0y7hXdwu4pDg2sCffq0MDmCawie-H3-eFZQ5oCi6U)

I can help you in resolving this setup issue. Connect with me

**Comment by thakur24** [comment]
> > Hi @gouravmore / Team , I'm trying to setup the project in local. And facing this issue. Can you pls help on this . Thanks ! ![image](https://private-user-images.githubusercontent.com/43248093/313617318-7ae0f135-461f-47aa-876a-0026ec9fd1da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTcwNTksIm5iZiI6MTcxMDc5Njc1OSwicGF0aCI6Ii80MzI0ODA5My8zMTM2MTczMTgtN2FlMGYxMzUtNDYxZi00N2FhLTg3NmEtMDAyNmVjOWZkMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIxMTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjODZkMjYyMTMwY2FlNTJkMDE0MTMxZDJjZTVjZDc0Zjg0MzJlMGI0NWRjM2I2NTQ5M2I4ZWQwMzEzNzAxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yU0y7hXdwu4pDg2sCffq0MDmCawie-H3-eFZQ5oCi6U)
> 
> I can help you in resolving this setup issue. Connect with me

hey @surajgorai2002 , thanks bro. Let me know how can i reach you , or if you can explain the issue on a high-level , that will work too.

**Comment by surajgorai2002** [comment]
> > > Hi @gouravmore / Team , I'm trying to setup the project in local. And facing this issue. Can you pls help on this . Thanks ! ![image](https://private-user-images.githubusercontent.com/43248093/313617318-7ae0f135-461f-47aa-876a-0026ec9fd1da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTcwNTksIm5iZiI6MTcxMDc5Njc1OSwicGF0aCI6Ii80MzI0ODA5My8zMTM2MTczMTgtN2FlMGYxMzUtNDYxZi00N2FhLTg3NmEtMDAyNmVjOWZkMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIxMTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjODZkMjYyMTMwY2FlNTJkMDE0MTMxZDJjZTVjZDc0Zjg0MzJlMGI0NWRjM2I2NTQ5M2I4ZWQwMzEzNzAxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yU0y7hXdwu4pDg2sCffq0MDmCawie-H3-eFZQ5oCi6U)
> > 
> > 
> > I can help you in resolving this setup issue. Connect with me
> 
> hey @surajgorai2002 , thanks bro. Let me know how can i reach you , or if you can explain the issue on a high-level , that will work too.


Connect me on LinkedIn : https://www.linkedin.com/in/suraj-gorai-a594a7211?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app


Else we connect on discord also as your wish

**Comment by PayalKumari10** [comment]
@surajgorai2002   i want to work on this issue plz assign me

**Comment by PayalKumari10** [comment]
Hi @gouravmore 

I'd like to work on this issue. I plan to:
1. Implement global search functionality for the story list using PrimeNG and JavaScript.
2. Enable search by story title, author, date, and other relevant criteria.
3. Ensure real-time updates of search results as the user types.
4. Utilize backend APIs for fetching filtered data.
Please let me know if there are any specific requirements. I look forward to contributing!
Thank you.

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 ,
Pls directly raise the PR. Do give us an indication here if you are working on it.
Thanks.

**Comment by PayalKumari10** [comment]
> Hello @PayalKumari10 , Pls directly raise the PR. Do give us an indication here if you are working on it. Thanks.

Thank you for the update. I've already started working on the issue and will raise the draft PR shortly. I'll keep you posted on the progress. Thanks @VedantKhairnar sir

**Comment by PayalKumari10** [comment]
**When I try to run this code. Getting this error?** 

![sunbird issue111111](https://github.com/user-attachments/assets/6faebf5a-3180-41d5-833f-05bff378b352)

**Comment by VedantKhairnar** [comment]
Hello @gouravmore ,
Will you pls help Payal with the error? Thanks.

**Comment by gouravmore** [comment]
Hi everyone,

Thank you all for your interest and contributions to this issue. We are currently planning to move the project to Next.js. Since the backend and frontend are currently separated, we are also consolidating them into a single repository to streamline development.

As a result, this specific issue will no longer be relevant in the new setup, and we are closing this ticket. We appreciate your efforts and encourage you to stay tuned for future opportunities to contribute as we move forward with the new structure.

**Comment by Asp-irin** [comment]
"Hey @gouravmore, if you need any help with transitioning the project to Next.js, I'd be happy to help!"
