### ISSUE TITLE
[C4GT Community]: Implementation of "Clear" Button for Clearing Filters

### ISSUE THREAD

**Issue by gouravmore** [Sunbird-ALL/all-config-app#11]
## Description
This ticket entails the implementation of a "Clear" button functionality within config application to enable users to easily clear all applied filters. The "Clear" button will enhance user experience by providing a convenient way to reset the filter settings and view the original, unfiltered content.

## Goals
 - [ ] Implement a "Clear" button within the filter interface.
- [ ]  Ensure that clicking the "Clear" button resets all applied filters to their default settings.
- [ ]  Enhance user accessibility and usability by providing clear feedback upon clearing filters.

### Expected Outcome

The final product should include a prominently displayed "Clear" button within the filter interface. When clicked, this button should reset all applied filters, returning the content to its original state without any filtering.

### Acceptance Criteria

- The "Clear" button should be clearly visible and accessible within the filter interface.
- Clicking the "Clear" button should reset all filter settings, including text inputs, dropdown selections, checkboxes, etc.
- Upon clearing filters, users should receive clear feedback confirming that the filters have been reset.

### Implementation Details

- The "Clear" button functionality will be implemented using JavaScript to manipulate the filter settings dynamically.
- Backend APIs, if applicable, may need to be called to reset any server-side filtering.
- Proper error handling and validation will be implemented to ensure the reliability and consistency of the "Clear" button functionality.

### Mockups/Wireframes

![clearbutton](https://github.com/Sunbird-ALL/all-config-app/assets/16605526/c30a6f38-a0c1-416f-af82-615ecf796221)

### Product Name

ALL Configurable app

### Organisation Name

Tekdi

### Tech Skills Needed

Angular

### Mentor(s)

@gou

### Complexity

Low

### Category

Frontend

**Comment by amansgith** [comment]
Hii @gouravmore i would like to work on this issue under your guidance... can you assign this to me and guide me to setup this repo locally
i tried setting it up but not getting any response on running the web app.. 
thank you

**Comment by surajgorai2002** [comment]
Hi @gouravmore , I would like to work on this issue. I have prior hands on experience in Angular . Can you please assign this task to me?

**Comment by prakhardotdeb** [comment]
hi @gouravmore , i feel that i have the necessary skills for this project and i would love to contribute. Could you please assign this ticket to me?

**Comment by psankhe28** [comment]
Hi @gouravmore, I'm interested in working on this task. In my previous role at a company, I was responsible for developing an Angular application. Additionally, I've contributed to a community project where I created visualizations using Angular and D3.js. I've already set up the project locally and am ready to start working on it. I'll submit a pull request as soon as possible.

**Comment by heyhimansh** [comment]
Hi @gouravmore  , I'm interested in working on the implementation of the "Clear" button functionality in the config application. It seems like a valuable addition to enhance user experience.

I have experience with JavaScript and front-end development, which I believe will be beneficial for implementing this feature effectively. Ensuring that the "Clear" button resets all applied filters and provides clear feedback to the users is something I can handle well.

**Comment by Vijaygaurav2004** [comment]
Hi @gouravmore, I'm eager to tackle this task as it aligns well with my expertise in JavaScript and front-end development. Could you please assign it to me

**Comment by Rushhaabhhh** [comment]
Hello @gouravmore, I have implemented the required things for the issue #17 , please review it and if there are any issues in the data, guide me to correct it.

**Comment by Kumar2004-2009** [comment]
Hi @gouravmore,  I'm interested in working on the implementation of the "Clear" button functionality.
i feel that i have the necessary skills for this project and i would love to contribute. Could you please assign this ticket to me?
I've already set up the project locally and am ready to start working on it. I'll submit a pull request as soon as possible.

**Comment by hardik-pratap-singh** [comment]
Hey @gouravmore !
I want to work on this issue under Augtoberfest, C4GT
Please assign this issue if possible..

**Comment by PayalKumari10** [comment]
Hello @gouravmore 

I'd like to contribute to this issue. My plan includes:
1. Implementing a "Clear" button within the filter interface.
2. Ensuring the button resets all applied filters to default settings.
3. Providing clear feedback to users upon clearing filters.
4. Using JavaScript for dynamic filter manipulation and calling backend APIs if needed.
Have I got the right idea? let me know if I am wrong; otherwise, Tell me so i start to working on it.
Thank you.

**Comment by VedantKhairnar** [comment]
Hello @PayalKumari10 @hardik-pratap-singh 
Pls directly raise the PR. Pls do give us an indication that you are working on the issue.
Thanks.

**Comment by PayalKumari10** [comment]
> Hello @PayalKumari10 @hardik-pratap-singh Pls directly raise the PR. Pls do give us an indication that you are working on the issue. Thanks.

Thank you for the update. I've already started working on the issue and will raise the draft PR shortly. I'll keep you posted on the progress. Thanks @VedantKhairnar sir

**Comment by gouravmore** [comment]
This functionality has been fixed in this PR https://github.com/Sunbird-ALL/all-config-app/pull/15
Hence closing this ticket.
