### ISSUE TITLE
[C4GT Community]: Implementation of Audio Upload for Contents

### ISSUE THREAD

**Issue by gouravmore** [Sunbird-ALL/all-config-app#13]
## Description
This ticket involves implementing audio upload functionality for contents within our application. Enabling users to upload audio files will enhance the diversity of content types available on our platform, providing a richer experience for our users.

### Goals

- [ ]  Implement audio upload functionality allowing users to upload audio files for contents.
- [ ]  Ensure that uploaded audio files are properly validated and stored securely.
- [ ]  Integrate audio upload seamlessly into the content creation workflow.

### Expected Outcome

The final product should include a user-friendly interface for uploading audio files when creating or editing content. Users should be able to upload audio files from their local devices and access them alongside other content.

### Acceptance Criteria

- Users should be able to upload audio files in common formats (e.g., MP3, WAV, AAC) from their local devices.
- Uploaded audio files should be properly validated for file type, size, and other relevant criteria.
- Uploaded audio files should be securely stored and associated with the respective content.
- The audio upload feature should be integrated seamlessly into the content creation/editing interface.

### Implementation Details

- The audio upload functionality will be implemented using backend APIs for file handling and storage.
- Frontend components will be developed using HTML and JavaScript to facilitate user interaction and audio file selection/upload.
- Proper error handling and validation will be implemented to ensure the reliability and security of the audio upload process.

### Mockups/Wireframes

![Audio upload](https://github.com/Sunbird-ALL/all-config-app/assets/16605526/2bab47c4-1d5a-408c-8717-022fc628bd1b)

### Product Name

ALL configurable app

### Organisation Name

Tekdi

### Tech Skills Needed

Angular

### Mentor(s)

@gour

### Complexity

High

### Category

Frontend

**Comment by vsvishalsharma** [comment]
@gouravmore ,@gour I would love to work on this issue just wanted to understand few things about this issue

**Comment by surajgorai2002** [comment]
Hi @gouravmore , I would like to work on this issue. I think my prior experience in Angular perfectly matches the requirements to resolve the issue.
Please Assign this task to me .

**Comment by rising0raj** [comment]
Hey @gouravmore I would like to work on this . I have gone through the code base can you assign this to me if it is open??

**Comment by Ris-code** [comment]
Hey @gouravmore. 
Could you assign me this issue? I have prior knowledge of working with Angular, and this issue will be a great one for me to contribute to.

**Comment by VishnuAmit** [comment]
Hello @gouravmore Hey, I am facing a couple of issues here. I cant see anything in the local host. Seems like couple of errors shown in Console. Can you please help me with this.?

**Comment by THECODEHUNT** [comment]
Hello @gouravmore Can you please assign me this issue?

**Comment by gouravmore** [comment]
@THECODEHUNT could you please share your approach/Steps for implementation to implementing this feature?

**Comment by THECODEHUNT** [comment]
Thanks for responding sir, I will send you my approach

**Comment by THECODEHUNT** [comment]
Steps for implementation to implementing this feature:-

https://1drv.ms/w/c/52e2538ced1cb5b8/EcWDOjNVpmBHmzvpJ4rfraoBzgcqP8qHXYc4bg0WXt6o6w?e=4DhHOz

**Comment by VedantKhairnar** [comment]
Hello @THECODEHUNT 
Are you currently open to working on this issue?
Thanks.

**Comment by THECODEHUNT** [comment]
> Hello @THECODEHUNT Are you currently open to working on this issue? Thanks.

Yes Sir

**Comment by VedantKhairnar** [comment]
Hello @THECODEHUNT 
Any update on the contribution?
Do let us know if you need any assistance.
Thanks.

**Comment by arun-maddheshia** [comment]
Hello @gouravmore  I am available to work on this issue. Could you please assign it to me if no one else is currently working on it?

**Comment by gouravmore** [comment]
Hi everyone,

Thank you all for your interest and contributions to this issue. We are currently planning to move the project to Next.js. Since the backend and frontend are currently separated, we are also consolidating them into a single repository to streamline development.

As a result, this specific issue will no longer be relevant in the new setup, and we are closing this ticket. We appreciate your efforts and encourage you to stay tuned for future opportunities to contribute as we move forward with the new structure.
